---
title: "Linear Regression"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Let's start with plain old OLS.  In STATA this is done using the command `reg`. In R, OLS is run using the commend `lm()`. This is part of base-R, which means that there are no packages to install, you just start R and you're ready to go. 

While STATA seperates each part of the regression with a space, R wraps everything in parentheses. You don't have to include any spaces between the elements inside the pathenses, but it best to do so, for readability. You do have to add `~`, `+`, and `:`. `~` goes between the dependent variabale, and the rest of the equation, `+` seperates the rest of the variables in an additive model, and `:` indicates a multiplitcative interation. So 
`lm(y ~ x1 + x2 + x1:x2, data = stata.data)` is the same as `gen x1x2 = x1*x2` followed by `reg y x1 x2 x1x2` in STATA.

This R code could also be written: 
```
lm(stata.data$y ~ stata.data$x1 + stata.data$x2 + stata.data$x1:stata.data$x2)
```
And just to add even more variety, one could also write:
```
attach(stata.data)
lm(y ~ x1 + x2 + x1:x2)
```

